name = "MagmaGroups"
uuid = "7acfbe5b-c34a-4b87-9116-540863c2b2a3"
authors = ["Tommy Hofmann <thofma@gmail.com> and contributors"]
version = "0.0.1"

[deps]
MagmaCall = "bbc12448-813b-4029-aa6c-5ca2c038c8b3"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
